/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Hacker {
    public static boolean isRequest(byte[] message) {
        return true;
    }

    public static short getId(byte[] message) {
        return 0;
    }

    public static short getQueryCount(byte[] message) {
        return 0;
    }

    public static String[] getDomain(byte[] message) {
        return new String[] {};
    }

    public static byte[] getResponse(short id, String[] domain) {
        return new byte[] {};
    }

    public static byte[][] filterRequests(byte[][] messages) {
        return new byte[][] {};
    }
}
